# Project information
site_name: 'learn2proGrAME Grundlagentutorial'
site_description: 'Das learn2proGrAME Grundlagentutorial zur Spieleprogrammierung mit C# in Unity'
site_author: 'learn2proGrAME'
site_url: 'https://learn2programe.github.io/learn2proGrAME-Grundlagen/'
nav:
    - Einleitung: 0110-index\0110-index.md
    - Bedienoberflächen: 0120-userinterface\0120-userinterface.md
    - Erste Schritte: 0130-firststeps\0130-firststeps.md
    - Fehler und De-Bugging: 0140-debugging\0140-debugging.md
    - Variablen: 0150-variables\0150-variables.md
    - Operatoren: 0160-operators\0160-operators.md
    - Spiel - Krapfenklicker: 0170-donutclicker\0170-donutclicker.md
    - Transform Spielobjektkomponente: 0180-transform\0180-transform.md
    - Verzweigungen: 0190-conditionals\0190-conditionals.md
    - Spiel - Ellis' großes Abenteuer: 0200-adventure\0200-adventure.md
    - Grafiken gestalten in GIMP: 0210-drawingingimp\0210-drawingingimp.md
    - Funktionen: 0220-functions\0220-functions.md
    - Zugriffskontrolle: 0230-accessmodifiers\0230-accessmodifiers.md
    - Spiel - Space-Asteroids: 0240-spaceshooter\0240-spaceshooter.md
    - Schleifen: 0250-loops\0250-loops.md
    - Die Spiel-Schleife: 0260-gameloop\0260-gameloop.md
    - Objekt-orientiertes Programmieren - Grundlagen: 0270-classes\0270-classes.md
    - Spiel - BouncyFant:  
      - Einführung: 0280-bouncyfant/T00-introduction.md
      - Teil 1 - Neues Projekt und Assets: 0280-bouncyfant/T01-adassets.md
      - Teil 2 - Animationen und States: 0280-bouncyfant/T02-animstat.md  
      - Teil 3 - Bewegung: 0280-bouncyfant/T03-movement.md
      - Teil 4 - Levels, Collider: 0280-bouncyfant/T04-levels.md
      - Teil 5 - Zweite Spielfigur: 0280-bouncyfant/T05-secondchar.md
      - Teil 6 - Jump Around: 0280-bouncyfant/T06-jump.md
      - Teil 7 - Physikwelt: 0280-bouncyfant/T07-physics.md
      - Teil 8 - Gewinnbedingung: 0280-bouncyfant/T08-win.md
      - Teil 9 - Finetuning: 0280-bouncyfant/T09-finetuning.md
    - Über learn2proGrAME: 0290-about\0290-about.md
    - Für Lehrpersonen: 0300-teachers\0300-teachers.md


# Repository
repo_name: 'learn2proGrAME/learn2proGrAME-Grundlagen'
repo_url: 'https://github.com/learn2proGrAME/learn2proGrAME-Grundlagen'

# Copyright
copyright: 'Copyright &copy; 2019 learn2proGrAME'

# Configuration
theme:
  name: 'material'
  language: 'de'
  palette:
    primary: 'light blue'
    accent: 'orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  highlightjs: true
  logo: 'img/elliLogo.png'


# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/learn2proGrAME'




# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - footnotes
  - pymdownx.details
